[33mcommit 76347f80d335adc7d87aaf61aee938f22b222782[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m, [m[1;31morigin/master[m[33m)[m
Author: Andrei Davidovici <andreiultp@web.de>
Date:   Wed Sep 7 09:30:00 2022 +0200

    Foto geloscht

[33mcommit 37b007df37d32fe1ad4743baf3decce0ba557315[m
Author: Andrei Davidovici <andreiultp@web.de>
Date:   Wed Sep 7 09:17:04 2022 +0200

    Erste Commit
